const GET_DATALIST_SAGA = "app/Task-App/GET_DATALIST_SAGA";
const SET_DATALIST_SAGA = "app/Task-App/SET_DATALIST_SAGA";

const GET_INSERT_USER_SAGA = "app/Task-App/GET_INSERT_USER_SAGA";
const SET_INSERT_USER_SAGA = "app/Task-App/SET_INSERT_USER_SAGA";

const GET_DELETE_USER_SAGA = "app/Task-App/GET_INSERT_USER_SAGA";
const SET_DELETE_USER_SAGA = "app/Task-App/SET_DELETE_USER_SAGA";

const GET_EDIT_USER_SAGA = "app/Task-App/GET_INSERT_USER_SAGA";
const SET_EDIT_USER_SAGA = "app/Task-App/SET_EDIT_USER_SAGA";

export { 
    GET_DATALIST_SAGA, 
    SET_DATALIST_SAGA,
    GET_INSERT_USER_SAGA,
    SET_INSERT_USER_SAGA,
    GET_DELETE_USER_SAGA,
    SET_DELETE_USER_SAGA,
    SET_EDIT_USER_SAGA,
    GET_EDIT_USER_SAGA
};
